# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

renumberPatchIds <- function(patchIds) {
    .Call(`_PopScape_renumberPatchIds`, patchIds)
}

patchdistcpp <- function(patches, popden) {
    .Call(`_PopScape_patchdistcpp`, patches, popden)
}

calculateConnectivity <- function(Ai, Oj, dij, alpha) {
    .Call(`_PopScape_calculateConnectivity`, Ai, Oj, dij, alpha)
}

calculatePatchSizes <- function(patches) {
    .Call(`_PopScape_calculatePatchSizes`, patches)
}

calculateAveragePatchQuality <- function(patches, qualities) {
    .Call(`_PopScape_calculateAveragePatchQuality`, patches, qualities)
}

ExtProb <- function(Ai, pden, mu, x) {
    .Call(`_PopScape_ExtProb`, Ai, pden, mu, x)
}

ColProb <- function(Ai, Oj, dij, alpha, gamma) {
    .Call(`_PopScape_ColProb`, Ai, Oj, dij, alpha, gamma)
}

runmetapopmodel <- function(patch, popden, res, dij, mu, x, alpha, gamma, timesteps) {
    .Call(`_PopScape_runmetapopmodel`, patch, popden, res, dij, mu, x, alpha, gamma, timesteps)
}

assignPatchValues <- function(patchIds, values) {
    .Call(`_PopScape_assignPatchValues`, patchIds, values)
}

PopSim_one <- function(Nt, K, birthrate, survival, dij, dispdist, fracdisp, emmsurv, Areas) {
    .Call(`_PopScape_PopSim_one`, Nt, K, birthrate, survival, dij, dispdist, fracdisp, emmsurv, Areas)
}

PopSim <- function(Nt, K, birthrate, survival, dij, dispdist, fracdisp, emmsurv, Areas) {
    .Call(`_PopScape_PopSim`, Nt, K, birthrate, survival, dij, dispdist, fracdisp, emmsurv, Areas)
}

arraytomat <- function(a, patchm) {
    .Call(`_PopScape_arraytomat`, a, patchm)
}

apply3D <- function(a) {
    .Call(`_PopScape_apply3D`, a)
}

mattoarray <- function(m, patchm) {
    .Call(`_PopScape_mattoarray`, m, patchm)
}

apply3Dv <- function(a) {
    .Call(`_PopScape_apply3Dv`, a)
}

